stages:
  - build
  - export

tikz-build:
  stage: build
  image: 
    name: danteev/texlive
  script:
    - cd images
    - find . -type f -name "*.tex" -exec latexmk -pdf {} \;
  artifacts:
    paths:
      - "images/*.pdf"

svg-export:
  stage: export
  image: 
    name: danteev/texlive
  script:
    - cd images
    - find . -type f -name "*.pdf" -exec sh -c "inkscape $1 --export-plain-svg=${1%.*}.svg" sh {} \;
  dependencies:
    - tikz-build
  artifacts:
    paths:
      - "images/*.svg"

png-export:
  stage: export
  image: 
    name: dpokidov/imagemagick
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - cd images
    - find . -type f -name "*.pdf" -exec sh -c "convert -density 300 $1 ${1%.*}.png" sh {} \;
  dependencies:
    - tikz-build
  artifacts:
    paths:
      - "images/*.png"
