tikz-build:
  stage: build
  image: 
    name: danteev/texlive
  script:
    - cd images
    - find . -type f -name "*.tex" -exec latexmk -pdf {} \;
    - find . -type f -name "*.pdf" -exec sh -c 'inkscape "$1" --export-plain-svg=${1%.*}.svg' sh {} \;
  artifacts:
    paths:
      - "images/*.pdf"
      - "images/*.svg"
