skiplist-build:
  stage: build
  image: gcc
  only:
    changes:
      - ".gitlab-ci.yml"
      - "src/*"
  script:
    - cd src
    - make test_skipliste
  artifacts:
    paths:
      - src/test_skipliste

skiplist-test:
  stage: test
  only:
    changes:
      - ".gitlab-ci.yml"
      - "src/*"
  script:
    - src/test_skipliste
  dependencies:
    - skiplist-build
